language: generic
sudo : required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t kiril/docker-react-dev .

script:
    - docker run -e CI=true kiril/docker-react-dev npm run test -- --coverage